name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pull-request-job
      - name: Run Unit Tests
        run: pnpm test:coverage
      # - uses: VeryGoodOpenSource/very_good_coverage@v2
      #   with:
      #     path: './coverage/lcov.info'
      #     min_coverage: 80
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pull-request-job
      - name: Lint
        run: pnpm lint
  bundle-size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pull-request-job
      - name: Build the app
        run: pnpm build
      - name: Bundlesize Check
        run: pnpm bundlesize
  playwright-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pull-request-job
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm playwright:run-integration
